spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true

# zuul做为后端负载均衡枢纽不推荐使用重试，因为重试会引起压力增大，可能会造成雪崩
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
